//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectVOG
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public int idEvent { get; set; }
        public string Title { get; set; }
        public System.DateTime Date { get; set; }
        public string Address { get; set; }
        public string Decription { get; set; }
        public Nullable<int> idUser { get; set; }
        public string Image { get; set; }
    
        public virtual User User { get; set; }
    }
}
