//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectVOG
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderTicket
    {
        public int idOrderTicket { get; set; }
        public int idOrder { get; set; }
        public int idTicket { get; set; }
        public int TicketCount { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Ticket Ticket { get; set; }
    }
}
