//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectVOG
{
    using System;
    using System.Collections.Generic;
    
    public partial class Surdoperevodchik
    {
        public int idSurdo { get; set; }
        public string SurnameSurdo { get; set; }
        public string NameSurdo { get; set; }
        public string FatherlandSurdo { get; set; }
        public string Phone { get; set; }
        public string Decription { get; set; }
        public int idGender { get; set; }
        public string PhotoSurdo { get; set; }
        public Nullable<int> idUser { get; set; }
    
        public virtual Gender Gender { get; set; }
        public virtual User User { get; set; }
    }
}
