//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectVOG
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ticket()
        {
            this.OrderTicket = new HashSet<OrderTicket>();
        }
    
        public int idTicket { get; set; }
        public string TitleMovie { get; set; }
        public System.DateTime DateMovie { get; set; }
        public int idGenre { get; set; }
        public string DecriptionMovie { get; set; }
        public decimal Cost { get; set; }
        public string Image { get; set; }
        public Nullable<int> idSinema { get; set; }
    
        public virtual Genre Genre { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderTicket> OrderTicket { get; set; }
        public virtual Sinema Sinema { get; set; }
    }
}
